# Enable mouse mode
set -g mouse on

# Scrollback
set-option -g history-limit 5000

# Copy from tmux to host
set-option -g set-clipboard on
set-window-option -g mode-keys vi
# Bind 'y' to copy selected text to the system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"

# Run .bashrc on start
set-option -g default-command "bash --login"
